### ISSUE TITLE
Doesn't seem to be working

### ISSUE THREAD

**Issue by itsbrex** [underscorephil/alfre-do#6]
Tried using your example format just to make sure I wasn't doing something wrong. I've tried setting a default list too, but no luck. Using latest 0.3 version with Alfred v2.8.2 (432) on Mac OS X 10.11.3 (15D21)

![czvic9lu1x](https://cloud.githubusercontent.com/assets/9772694/13478690/14e14a8e-e087-11e5-8f8e-56459ea2b5fb.gif)

**Comment by ninthspace** [comment]
For v2.0 and above of 2Do, x-callback-url is required. See http://www.2doapp.com/kb/article/url-scheme-supported-by-2do-for-apps-like-launch-center-pro.html

Until it's repackaged, this is what I did to resolve:
- In Workflows, use 'Show in Finder' to reveal alfre-do
- Edit 2do.py, modifying on line 46:

`url = 'twodo:///add?task=%s&forlist=%s' % (task_title, twodo_list)`

to

`url = 'twodo://x-callback-url/add?task=%s&forlist=%s' % (task_title, twodo_list)`

and Save.

**Comment by itsbrex** [comment]
Oh perfect. I was looking at that documentation yesterday, but didn't realize the current Mac app is newer than that documentation listed it at. Works great now. Thanks @ninthspace!

**Comment by underscorephil** [comment]
Thanks @ninthspace!

BTW I am not actively using 2do anymore. If anyone is interested in maintaining this please let me know.

**Comment by itsbrex** [comment]
@underscorephil I suppose I am interested. I'm relatively new to programming and am unsure of the process of taking it over, but I am willing to learn. :+1:

**Comment by underscorephil** [comment]
@brianroach Shoot me an email on the account listed in my profile. Happy to help you get on your feet with it. Dont want to see this die as people are getting use from it.

**Comment by underscorephil** [comment]
@brianroach my email to you has been bouncing with "Technical details of temporary failure:
The recipient server did not accept our requests to connect." Have an alternate?

**Comment by itsbrex** [comment]
shoot, sorry about that. having google apps issues. roach7@gmail.com

**Comment by mattburman** [comment]
Thanks @ninthspace 

Maybe you should maintain it if not @brianroach ? Either way, submit a pull request with that fix then we can make a new release 👍

cc @underscorephil
